package com.lingfenglong.mybatis.mappers;

import com.lingfenglong.mybatis.pojo.Employee;
import com.lingfenglong.mybatis.pojo.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Tue Jul 25 10:29:14 CST 2023
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Tue Jul 25 10:29:14 CST 2023
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Tue Jul 25 10:29:14 CST 2023
     */
    int insert(Employee row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Tue Jul 25 10:29:14 CST 2023
     */
    int insertSelective(Employee row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Tue Jul 25 10:29:14 CST 2023
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Tue Jul 25 10:29:14 CST 2023
     */
    int updateByExampleSelective(@Param("row") Employee row, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Tue Jul 25 10:29:14 CST 2023
     */
    int updateByExample(@Param("row") Employee row, @Param("example") EmployeeExample example);
}